language: android
android:
  components:
    - android-27
    - build-tools-27.0.3

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

before_install:
    - chmod +x gradlew 
    - echo yes | sdkmanager "build-tools;27.0.3"

#  Run assemble and unit tests
script:
  - chmod +x ./gradlew  
  - clean
  #- ./gradlew clean 
  #assembleDebug assembleRelease testDebug
  

